/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'dmb' at '10/16/16 10:09 PM' with Gradle 2.10
 *
 * @author dmb, @date 10/16/16 10:09 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
